Config database ativos
fga-eps-mds/GFour-Invext pull request #69
Opened 2022-08-12 18:45 UTC by LeonardoPadre

#### O que essa PR faz?
  Adiciona a proteção de rotas e o banco de dados dos ativos.
#### Tarefas desenvolvidas:

  - Foi criado o banco de dados dos ativos.
  - Criação do middleware para proteção de rotas que necessitam de autenticação para serem acessadas.
  
#### Link relacionada a issue: [Link da issue](https://github.com/fga-eps-mds/GFour-Invext/issues/61#issue-1329265615)

2022-08-13 18:19 UTC, amanda-noda approved these changes

2022-08-15 14:24 UTC, luciano-freitas-melo requested changes
Algumas dúvidas precisam ser respondidas antes de conseguirmos dar o merge sem problemas

2022-08-15 14:24 UTC, luciano-freitas-melo commented on Back/src/controller/AtivoController.js
> +    } else {
Isso aqui vai dar problema depois, pois não deixa eu comprar/vender o mesmo ativo

2022-08-15 14:24 UTC, luciano-freitas-melo commented on Back/src/controller/AtivoController.js
> +    const novo_ativo = {
Aqui, o id do usuario já não é inserido direto no backend?

2022-08-15 22:07 UTC, lucasgcaldas commented on Back/src/controller/AtivoController.js
> +    if (novo_ativo.sigla === null) {
No caso ai, se você olhar desde o começo a gente definiu a variável como null inicialmente, ou seja, se voce entrar no back com um ativo "BOLINHA123", ele vai fazer uma busca primeiro na api da b3 e vai ver se tem, se não tiver, continua como null "novo_ativo.sigla", por isso que tem esse if.

2022-08-15 22:07 UTC, lucasgcaldas commented on Back/src/controller/AtivoController.js
> +    if (novo_ativo.sigla === null) {
Fizemos assim, pois precisamos da parte do front pronta para criar a busca certinha, mas em breve isso ai será mudado!

2022-08-15 22:11 UTC, lucasgcaldas commented on Back/src/controller/AtivoController.js
> +    } else {
A gente tinha tratado diferente a forma como comprar ou vender, no caso seria aumentar a posição ou diminuir, mas a gente pode criar uma coluna na tabela que fala qual foi o tipo de operação(compra ou venda), que eu acho até melhor.

2022-08-15 22:12 UTC, lucasgcaldas commented on Back/src/controller/AtivoController.js
> +    const novo_ativo = {
sim, deveria ser automático, porém ainda não está

2022-08-15 23:33 UTC, luciano-freitas-melo approved these changes

2022-08-16 00:58 UTC, merged